
export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

export const TIMER_OPTIONS = [60, 90];

export const TEAMS = [
  { id: 0, color: 'bg-red-500', text: 'text-red-500', border: 'border-red-500', ring: 'ring-red-500', label: 'ROJO' },
  { id: 1, color: 'bg-blue-500', text: 'text-blue-500', border: 'border-blue-500', ring: 'ring-blue-500', label: 'AZUL' },
  { id: 2, color: 'bg-green-500', text: 'text-green-500', border: 'border-green-500', ring: 'ring-green-500', label: 'VERDE' },
  { id: 3, color: 'bg-yellow-500', text: 'text-yellow-500', border: 'border-yellow-500', ring: 'ring-yellow-500', label: 'AMARILLO' },
];

export const TEAMS_ADULT = [
  { id: 0, color: 'bg-pink-600', text: 'text-pink-600', border: 'border-pink-600', ring: 'ring-pink-600', label: 'ROSA' },
  { id: 1, color: 'bg-violet-600', text: 'text-violet-600', border: 'border-violet-600', ring: 'ring-violet-600', label: 'VIOLETA' },
  { id: 2, color: 'bg-teal-600', text: 'text-teal-600', border: 'border-teal-600', ring: 'ring-teal-600', label: 'VERDE AGUA' },
  { id: 3, color: 'bg-orange-500', text: 'text-orange-500', border: 'border-orange-500', ring: 'ring-orange-500', label: 'NARANJA' },
];

export const CATEGORIES = [
  "Nombres de mujer", "Nombres de hombre", "Apellidos", "Países", "Capitales del mundo",
  "Ciudades de Argentina", "Barrios", "Animales de 4 patas", "Animales que vuelan",
  "Animales marinos", "Frutas", "Verduras", "Colores", "Partes del cuerpo humano",
  "Prendas de ropa", "Marcas de ropa", "Marcas de autos", "Deportes", "Instrumentos musicales",
  "Profesiones", "Oficios", "Idiomas", "Plantas", "Películas", "Series de TV",
  "Series de streaming", "Dibujos animados", "Animé", "Villanos de ficción",
  "Superhéroes", "Actores", "Actrices", "Cantantes", "Bandas", "Canciones",
  "Youtubers", "Streamers", "Influencers", "Personajes de Disney", "Juegos de mesa",
  "Videojuegos", "Redes sociales", "Apps", "Marcas de tecnología", "Géneros musicales",
  "Frases famosas de películas", "Programas de TV argentinos", "Marcas de golosinas",
  "Personajes históricos", "Escritores", "Libros", "Equipos de fútbol",
  "Cosas que encontrás en una heladera", "Cosas que llevás en la cartera",
  "Cosas que llevás en la mochila", "Cosas que se pierden siempre",
  "Cosas que se rompen fácil", "Excusas para llegar tarde", "Motivos para cortar con tu pareja",
  "Cosas que comprarías si ganaras la lotería", "Cosas que encontrás en un baño",
  "Cosas que encontrás debajo de la cama", "Cosas que hacen ruido", "Cosas que huelen mal",
  "Cosas que huelen bien", "Cosas pegajosas", "Cosas redondas", "Cosas que hay en una fiesta",
  "Cosas que te dan miedo", "Fobias", "Cosas que te hacen feliz", "Regalos que no te gustarían",
  "Palabras para insultar", "Gritos de cancha", "Aliento de cancha", "Ingredientes de cocina",
  "Sabores de helado", "Sabores de postres", "Utensilios de cocina", "Comidas que se comen con la mano",
  "Platos típicos argentinos", "Bebidas con alcohol", "Bebidas sin alcohol", "Software",
  "Programas de PC", "Partes de una computadora", "Formatos de archivo", "Términos de internet",
  "Marcas de electrodomésticos", "Verbos en infinitivo", "Adjetivos para describir a una persona",
  "Palabras esdrújulas", "Palabras que terminan en “ón”", "Palabras en inglés que usamos en español",
  "Sentimientos", "Emociones", "Nombres de marcas que ya no existen", "Elementos de la tabla periódica",
  "Cosas que flotan", "Cosas que se derriten", "Cosas que encontrás en la playa",
  "Cosas que encontrás en la basura", "Cosas frías", "Cosas calientes",
  "Cosas que cuestan menos de 1000 pesos", "Cosas que cuestan muy caro", "Cosas que pesan mucho",
  "Cosas que entran en un bolsillo", "Cosas que hay en un auto", "Cosas que se compran en farmacia",
  "Cosas que se compran en ferretería", "Cosas que hay en un aula", "Animales extintos",
  "Marcas de cigarrillos", "Cortes de carne", "Apodos cariñosos", "Palabras que riman con “amor”",
  "Palabras de 4 letras", "Comidas picantes", "Comidas dulces", "Comidas de desayuno",
  "Comidas rápidas", "Comidas saludables", "Comidas fritas", "Comidas que odiás", "Famosos rubios",
  "Famosos muertos", "Famosos polémicos", "Famosos argentinos", "Marcas de zapatillas deportivas",
  "Ingredientes de pizza", "Cosas que se llevan a un picnic", "Cosas que se rompen en una mudanza",
  "Accesorios para el pelo", "Tipos de tela", "Partes de una bicicleta", "Apps de mensajería",
  "Juegos de plaza", "Cosas que comprás en un kiosco", "Títulos de novelas famosas",
  "Marcas de yerba mate", "Razas de perros", "Insectos", "Animales de granja",
  "Animales de la selva", "Animales del desierto", "Animales", "Cosas que brillan en la oscuridad",
  "Objetos transparentes", "Líquidos que no se toman", "Cosas pegadas a la pared",
  "Elementos químicos", "Piedras preciosas", "Metales", "Nombres de planetas", "Estrellas famosas",
  "Muebles de cocina", "Muebles de dormitorio", "Accesorios de baño", "Electrodomésticos grandes",
  "Electrodomésticos pequeños", "Herramientas manuales", "Herramientas eléctricas", "Útiles escolares",
  "Cosas que hay en una cartuchera", "Cosas que hay en una valija", "Países de América del Sur",
  "Países de Europa", "Próceres", "Marcas de perfumes", "Marcas de maquillaje",
  "Productos de higiene personal", "Productos de limpieza", "Cosas reciclables",
  "Fenómenos naturales", "Frutos secos", "Especias", "Condimentos", "Salsas para pastas",
  "Tipos de fideos", "Tipos de pan", "Facturas", "Cortes de carne vacuna", "Achuras",
  "Pescados para cocinar", "Mariscos", "Tipos de queso", "Fiambres", "Embutidos",
  "Sabores de empanadas", "Gustos de pizza", "Golosinas de la infancia", "Galletitas dulces",
  "Galletitas saladas", "Marcas de cerveza", "Tragos", "Cócteles", "Variedades de vino",
  "Cosas que se comen en Navidad"
];

export const CATEGORIES_ADULT = [
  "Zonas erógenas del cuerpo", "Lugares prohibidos para hacerlo", "Juguetes para adultos", "Puteadas",
  "Apodos para tus partes íntimas", "Cosas que se hacen en la cama (además de dormir)",
  "Lugares incómodos para tener sexo", "Excusas para no hacerlo", "Alimentos afrodisíacos",
  "Cosas que se usan como lubricante (cuando no hay)", "Fetiches comunes", "Disfraces sexys",
  "Actores / Actrices porno (o famosos que parecen)", "Apps de citas (o para buscar sexo)",
  "Insultos cariñosos en la intimidad", "Cosas que encontrás en un telo (hotel alojamiento)",
  "Partes del cuerpo que te gusta que te toquen", "Cosas que te bajan la libido (matapasiones)",
  "Lugares públicos donde te gustaría hacerlo", "Posiciones (reales o inventadas con la letra)",
  "Cosas que se dicen después de terminar", "Mentiras que se dicen en la cama", "Tipos de besos",
  "Lugares del cuerpo donde besar", "Canciones para hacer el amor", "Cosas que se pueden chupar",
  "Cosas que vibran", "Nombres de strippers (estereotípicos)", "Partes del cuerpo de un hombre que atraen",
  "Partes del cuerpo de una mujer que atraen", "Verbos relacionados con el sexo",
  "Objetos que se pueden usar para atar a alguien", "Sabores de preservativos", "Cosas que harías en un trío",
  "Secretos que no le contarías a tu pareja", "Cosas que se desnudan", "Palabras que riman con “sexo”",
  "Palabras que riman con “pene”", "Palabras que riman con “vagina” (o sinónimos)",
  "Situaciones donde es peligroso excitarse", "Ropa que es fácil de quitar", "Ropa que es difícil de quitar",
  "Cosas que manchan las sábanas", "Nombres de tragos que suenan sexuales",
  "Famosos con los que tendrías una noche loca", "Profesiones con uniformes sexys", "Cosas que se hacen en un auto",
  "Cosas que no te gustaría que te hagan", "Olores corporales (buenos o malos)", "Adjetivos para describir un orgasmo",
  "Cosas que decís cuando te gusta", "Sinónimos de “masturbarse”", "Sinónimos de “tener sexo”",
  "Cosas que te gustaría ver en una película porno", "Partes del cuerpo que se depilan",
  "Tatuajes en lugares ocultos", "Piercings en lugares íntimos", "Cosas que harías si fueras invisible (versión pervertida)",
  "Errores comunes en el sexo", "Cosas que dan vergüenza comprar en la farmacia",
  "Nombres que suenan a “gato” o “mujeriego”", "Frases para levantar / ligar en un boliche", "Propuestas indecentes",
  "Beneficios de estar soltero/a", "Razas para volver con un ex", "Sinonimos de sexo (palabra o frases)",
  "Parafilias", "Verbos de acción sexual", "Adjetivos para describir un pene",
  "Adjetivos para describir una vagina o vulva", "Fluidos corporales", "Motivos para hacer un \"ghosting\"",
  "Tipos de ropa interior", "ETS o ITS", "Métodos anticonceptivos", "Drogas o sustancias de fiesta"
];